name: heroku

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      actions:
        description: "deploy/stop/start"
        default: "deploy"

env:
  actions: ${{ github.event.inputs.actions }}

jobs:
  heroku-deploy:
    if: ${{ $actions == 'deploy' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.APP_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.EMAIL}}
          usedocker: true
          # docker_build_args: |
          #   NODE_ENV
          #   SECRET_KEY
        env:
          # 这是为了heroku，注意前缀有个HD，这是为了告诉heroku-deploy，这些变量需要传入到container 中。
          HD_UUID: ${{ secrets.HEROKU_V2RAY_UUID }} # UUID for v2ray user, 为了安全，一定要放入github action token中
          NODE_ENV: production
          SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
  stop:
    if: ${{ $actions  == 'start' || $actions  == 'stop' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.APP_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.EMAIL}}
          justlogin: true
      - run: |
          echo ${{ actions }}
          if [[ ${{ actions }} == 'stop' ]]; then echo "stop" && echo "dd"; fi
          if [[ ${{ actions }} == 'start' ]]; then echo "start" && echo "dd"; fi
          heroku auth:whoami
