name: heroku-deploy

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      actions:
        description: "deploy/stop/start"
        default: "deploy"

jobs:
  heroku-deploy:
    if: ${{ github.event.inputs.actions }} == 'deploy'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "testinput: ${{ github.event.inputs.testinput }}"
      - uses: actions/checkout@latest
      - uses: akhileshns/heroku-deploy@latest # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.APP_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.EMAIL}}
          usedocker: true
          # docker_build_args: |
          #   NODE_ENV
          #   SECRET_KEY
        env:
          NODE_ENV: production
          SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
          UUID: ${{ secrets.HEROKU_V2RAY_UUID }}
