name: shell-test

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  shell-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          echo "Run a multi-line script"
      - id: foo
        uses: ./.github/actions
        with:
          who-to-greet: "Mona the Octocat"
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
